/** @type {import('tailwindcss').Config} */
module.exports = {
	daisyui: {
		themes: [
			"light",
			"dark",
			"cupcake",
			"bumblebee",
			"emerald",
			"corporate",
			"synthwave",
			"retro",
			"cyberpunk",
			"valentine",
			"halloween",
			"garden",
			"forest",
			"aqua",
			"lofi",
			"pastel",
			"fantasy",
			"wireframe",
			"black",
			"luxury",
			"dracula",
			"cmyk",
			"autumn",
			"business",
			"acid",
			"lemonade",
			"night",
			"coffee",
			"winter",
			"dim",
			"nord",
			"sunset",
		],
	},
	content: ["./src/**/*.{html,js}"],
	theme: {
		extend: {},
		container: {
			center: true,
		},
	},
	plugins: [
		require("tailwindcss"),
		require("autoprefixer"),
		require("@tailwindcss/typography"),
		require("daisyui"),
	],
};
